apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld-server.fullname" . }}
  labels:
    app: {{ include "palworld-server.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.gamePort }}
      targetPort: game
      protocol: UDP
      name: game
    - port: {{ .Values.service.queryPort }}
      targetPort: query
      protocol: UDP
      name: query
  selector:
    app: {{ include "palworld-server.name" . }}
    release: {{ .Release.Name }}
